package steps

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/jackh0006/openvpn-stealth-wizard/internal/cfg"
	"github.com/jackh0006/openvpn-stealth-wizard/internal/logx"
)

const (
	serverDir  = "/etc/openvpn/server"
	usersDir   = "/etc/openvpn/users"
	authScript = "/etc/openvpn/check-pass.sh"
)

// PKI creates CA + server + client certificates with openssl and a
// tls-crypt key via openvpn. Skips anything already present.
type PKI struct{}

func (PKI) ID() string    { return "pki" }
func (PKI) Title() string { return "Build secret keys (PKI)" }
func (PKI) Why() string {
	return "Secret keys are like toothbrushes: the server and each phone get their own, never shared."
}

func (PKI) Check(c cfg.Config) Result {
	for _, f := range []string{"ca.crt", "server.crt", "server.key", "tls-crypt.key"} {
		if !fileExists(filepath.Join(serverDir, f)) {
			return Result{false, "missing " + f}
		}
	}
	return Result{true, "CA + server keys present"}
}

func (PKI) Apply(ctx context.Context, c cfg.Config, log *logx.Logger) error {
	pki := "/etc/openvpn/wizard-pki"
	if err := os.MkdirAll(pki, 0o700); err != nil {
		return err
	}
	if err := os.MkdirAll(serverDir, 0o700); err != nil {
		return err
	}
	mk := func(src, dst string) {
		if !fileExists(dst) && fileExists(src) {
			if b, err := os.ReadFile(src); err == nil {
				_ = os.WriteFile(dst, b, 0o600)
				log.Dim("kept existing " + dst)
			}
		}
	}
	_ = mk
	if fileExists(filepath.Join(serverDir, "ca.crt")) {
		log.OK("PKI already exists, keeping it")
		return nil
	}
	subj := func(cn string) string {
		return fmt.Sprintf("/CN=%s/O=CompanyVPN", cn)
	}
	run := func(name string, args ...string) error {
		log.Dim("$ " + name + " " + strings.Join(args, " "))
		return Run(ctx, log, name, args...)
	}
	if err := run("openssl", "genrsa", "-out", pki+"/ca.key", "2048"); err != nil {
		return err
	}
	if err := run("openssl", "req", "-x509", "-new", "-nodes", "-key", pki+"/ca.key",
		"-sha256", "-days", "3650", "-out", pki+"/ca.crt", "-subj", subj("company-ca")); err != nil {
		return err
	}
	if err := run("openssl", "genrsa", "-out", pki+"/server.key", "2048"); err != nil {
		return err
	}
	if err := run("openssl", "req", "-new", "-key", pki+"/server.key",
		"-out", pki+"/server.csr", "-subj", subj("server")); err != nil {
		return err
	}
	ext := "basicConstraints=CA:FALSE\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\n"
	if err := os.WriteFile(pki+"/server.ext", []byte(ext), 0o600); err != nil {
		return err
	}
	if err := run("openssl", "x509", "-req", "-in", pki+"/server.csr",
		"-CA", pki+"/ca.crt", "-CAkey", pki+"/ca.key", "-CAcreateserial",
		"-days", "825", "-sha256", "-extfile", pki+"/server.ext",
		"-out", pki+"/server.crt"); err != nil {
		return err
	}
	if err := run("openvpn", "--genkey", "secret", pki+"/tls-crypt.key"); err != nil {
		return err
	}
	if err := run("openssl", "genrsa", "-out", pki+"/client.key", "2048"); err != nil {
		return err
	}
	if err := run("openssl", "req", "-new", "-key", pki+"/client.key",
		"-out", pki+"/client.csr", "-subj", subj("client")); err != nil {
		return err
	}
	cext := "basicConstraints=CA:FALSE\nkeyUsage=digitalSignature\nextendedKeyUsage=clientAuth\n"
	if err := os.WriteFile(pki+"/client.ext", []byte(cext), 0o600); err != nil {
		return err
	}
	if err := run("openssl", "x509", "-req", "-in", pki+"/client.csr",
		"-CA", pki+"/ca.crt", "-CAkey", pki+"/ca.key", "-CAcreateserial",
		"-days", "825", "-sha256", "-extfile", pki+"/client.ext",
		"-out", pki+"/client.crt"); err != nil {
		return err
	}
	if err := run("openssl", "dhparam", "-out", filepath.Join(serverDir, "dh.pem"), "2048"); err != nil {
		return err
	}
	for _, f := range []string{"ca.crt", "server.crt", "server.key", "tls-crypt.key"} {
		b, err := os.ReadFile(pki + "/" + f)
		if err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(serverDir, f), b, 0o600); err != nil {
			return err
		}
	}
	log.OK("fresh PKI installed in " + serverDir)
	return nil
}

// ServerConf writes the stealth server config: TCP on 443 with
// port-share website camouflage and password auth via-file.
type ServerConf struct{}

func (ServerConf) ID() string    { return "server" }
func (ServerConf) Title() string { return "Write VPN server config" }
func (ServerConf) Why() string {
	return "One door (port 443) serves two guests: VPN apps go to the tunnel, browsers get a normal website."
}

func serverConfText(c cfg.Config) string {
	authBlock := ""
	if !c.NoPassword {
		authBlock = fmt.Sprintf("script-security 2\nauth-user-pass-verify %s via-file\nusername-as-common-name\nauth-nocache\n", authScript)
	}
	dns1, dns2 := c.DNS1, c.DNS2
	if dns1 == "" {
		dns1 = "1.1.1.1"
	}
	if dns2 == "" {
		dns2 = "1.0.0.1"
	}
	return fmt.Sprintf(`# Generated by openvpn-stealth-wizard. Safe to re-run.
port %d
proto tcp-server
dev tun
ca %s/ca.crt
cert %s/server.crt
key %s/server.key
dh %s/dh.pem
tls-crypt %s/tls-crypt.key
topology subnet
server %s %s
ifconfig-pool-persist /etc/openvpn/ipp.txt
route %s %s
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS %s"
push "dhcp-option DNS %s"
data-ciphers AES-256-GCM:AES-128-GCM
data-ciphers-fallback AES-256-GCM
auth SHA256
tls-version-min 1.2
%sverify-client-cert require
sndbuf 0
rcvbuf 0
push "sndbuf 393216"
push "rcvbuf 393216"
tcp-nodelay
tun-mtu 1400
mssfix 1200
keepalive 10 60
persist-key
persist-tun
port-share 127.0.0.1 8443
user nobody
group nogroup
remote-cert-tls client
max-clients 100
status /var/log/openvpn-status.log
log-append /var/log/openvpn.log
verb 3
explicit-exit-notify 0
`, c.Port,
		serverDir, serverDir, serverDir, serverDir, serverDir,
		subnetIP(c.Subnet), subnetMask(c.Subnet), subnetIP(c.Subnet), subnetMask(c.Subnet),
		dns1, dns2, authBlock)
}

func subnetIP(cidr string) string {
	if i := strings.Index(cidr, "/"); i > 0 {
		return cidr[:i]
	}
	return cidr
}

func subnetMask(cidr string) string {
	masks := map[string]string{"24": "255.255.255.0", "16": "255.255.0.0", "8": "255.0.0.0"}
	if i := strings.Index(cidr, "/"); i > 0 {
		if m, ok := masks[cidr[i+1:]]; ok {
			return m
		}
	}
	return "255.255.255.0"
}

func (ServerConf) Check(c cfg.Config) Result {
	b, err := os.ReadFile(filepath.Join(serverDir, "server.conf"))
	if err != nil {
		return Result{false, "server.conf missing"}
	}
	s := string(b)
	must := []string{fmt.Sprintf("port %d", c.Port), "port-share 127.0.0.1 8443"}
	if !c.NoPassword {
		must = append(must, "auth-user-pass-verify "+authScript+" via-file")
	}
	for _, want := range must {
		if !strings.Contains(s, want) {
			return Result{false, "server.conf lacks: " + want}
		}
	}
	if c.NoPassword && strings.Contains(s, "auth-user-pass-verify") {
		return Result{false, "server.conf still has password auth (should be cert-only)"}
	}
	return Result{true, "server.conf matches wizard spec"}
}

func (ServerConf) Apply(ctx context.Context, c cfg.Config, log *logx.Logger) error {
	backup(filepath.Join(serverDir, "server.conf"), log)
	if err := os.WriteFile(filepath.Join(serverDir, "server.conf"),
		[]byte(serverConfText(c)), 0o600); err != nil {
		return err
	}
	log.OK("server.conf written")
	if err := Run(ctx, log, "systemctl", "restart", "openvpn-server@server"); err != nil {
		return err
	}
	return Run(ctx, log, "systemctl", "is-active", "openvpn-server@server")
}

// WebCamouflage parks the nginx 443 stream (if any) and serves a real
// decoy website on 127.0.0.1:8443 behind port-share.
type WebCamouflage struct{}

func (WebCamouflage) ID() string    { return "web" }
func (WebCamouflage) Title() string { return "Website camouflage" }
func (WebCamouflage) Why() string {
	return "Anyone knocking on 443 with a browser sees a boring company page, not a VPN."
}

func (WebCamouflage) Check(c cfg.Config) Result {
	if !fileExists("/etc/nginx/sites-enabled/vpn-camouflage") {
		return Result{false, "camouflage site missing"}
	}
	return Result{true, "camouflage site present"}
}

func (WebCamouflage) Apply(ctx context.Context, c cfg.Config, log *logx.Logger) error {
	if data, err := os.ReadFile("/etc/nginx/nginx.conf"); err == nil {
		s := string(data)
		if strings.Contains(s, "include /etc/nginx/stream-sni.conf;") {
			backup("/etc/nginx/nginx.conf", log)
			s = strings.ReplaceAll(s, "include /etc/nginx/stream-sni.conf;",
				"#include /etc/nginx/stream-sni.conf; # parked by wizard (OpenVPN owns 443)")
			if err := os.WriteFile("/etc/nginx/nginx.conf", []byte(s), 0o644); err != nil {
				return err
			}
			log.Dim("parked nginx 443 stream")
		}
	}
	cert := "/etc/letsencrypt/live/" + c.Host + "/fullchain.pem"
	key := "/etc/letsencrypt/live/" + c.Host + "/privkey.pem"
	if c.Mode == cfg.ModeIP || !fileExists(cert) {
		log.Dim("no Let's Encrypt cert for " + c.Host + "; using snakeoil placeholder")
	}
	site := `server {
    listen 127.0.0.1:8443 ssl;
    server_name ` + c.Host + `;
    ssl_certificate ` + cert + `;
    ssl_certificate_key ` + key + `;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    root /var/www/html;
    index index.html;
    location / { try_files $uri $uri/ =404; }
}
`
	if err := os.WriteFile("/etc/nginx/sites-available/vpn-camouflage", []byte(site), 0o644); err != nil {
		return err
	}
	if err := os.Symlink("/etc/nginx/sites-available/vpn-camouflage",
		"/etc/nginx/sites-enabled/vpn-camouflage"); err != nil && !os.IsExist(err) {
		return err
	}
	page := `<!DOCTYPE html>
<html><head><title>Welcome</title></head>
<body style="font-family:sans-serif;max-width:640px;margin:60px auto;color:#333">
<h1>Welcome to our website</h1>
<p>Company portal. Please contact IT for access.</p>
</body></html>
`
	if !fileExists("/var/www/html/index.html") {
		_ = os.WriteFile("/var/www/html/index.html", []byte(page), 0o644)
	}
	if err := Run(ctx, log, "nginx", "-t"); err != nil {
		return err
	}
	return Run(ctx, log, "systemctl", "reload-or-restart", "nginx")
}
