package steps

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/jackh0006/openvpn-stealth-wizard/internal/cfg"
	"github.com/jackh0006/openvpn-stealth-wizard/internal/logx"
)

// PasswordAuth creates the via-file password checker. via-file is used
// (not via-env) because systemd-sandboxed daemons can lose env vars.
type PasswordAuth struct{}

func (PasswordAuth) ID() string    { return "auth" }
func (PasswordAuth) Title() string { return "Password login" }
func (PasswordAuth) Why() string {
	return "A stolen phone file alone is useless: the app must also know the password."
}

const checkPassScript = `#!/bin/bash
# Generated by openvpn-stealth-wizard. via-file: $1 holds user line 1, pass line 2.
[ -n "$1" ] && [ -f "$1" ] || exit 1
U=$(sed -n "1p" "$1"); P=$(sed -n "2p" "$1")
F="/etc/openvpn/users/$U"
[ -f "$F" ] || exit 1
S=$(cat "$F")
[ -n "$P" ] && [ "$P" = "$S" ] && exit 0
exit 1
`

func (PasswordAuth) Check(c cfg.Config) Result {
	b, err := os.ReadFile(authScript)
	if err != nil || !strings.Contains(string(b), "via-file") {
		return Result{false, "auth script missing"}
	}
	u, err := os.ReadFile(filepath.Join(usersDir, c.VPNUser))
	if err != nil || strings.TrimSpace(string(u)) != c.VPNPass {
		return Result{false, "user password not set"}
	}
	return Result{true, "user " + c.VPNUser + " can log in"}
}

func (PasswordAuth) Apply(ctx context.Context, c cfg.Config, log *logx.Logger) error {
	if err := os.MkdirAll(usersDir, 0o755); err != nil {
		return err
	}
	backup(authScript, log)
	if err := os.WriteFile(authScript, []byte(checkPassScript), 0o755); err != nil {
		return err
	}
	uf := filepath.Join(usersDir, c.VPNUser)
	if err := os.WriteFile(uf, []byte(c.VPNPass), 0o644); err != nil {
		return err
	}
	if err := exec.Command("chown", "nobody:nogroup", uf).Run(); err != nil {
		log.Dim("chown nobody skipped (nobody user missing?)")
	}
	log.OK("password set for " + c.VPNUser)
	return nil
}

// Network enables forwarding, NAT masquerade (persisted), UFW routes
// and the kernel route back into the tunnel.
type Network struct{}

func (Network) ID() string    { return "net" }
func (Network) Title() string { return "Internet for VPN users" }
func (Network) Why() string {
	return "The tunnel is a road; now we open the gates so traffic can actually drive through."
}

func (Network) Check(c cfg.Config) Result {
	out, _ := Output("iptables", "-t", "nat", "-L", "POSTROUTING", "-n")
	if !strings.Contains(out, c.Subnet) && !strings.Contains(out, "10.8.0.0") {
		return Result{false, "NAT masquerade missing"}
	}
	out, _ = Output("ip", "route", "get", "10.8.0.2")
	if !strings.Contains(out, "tun0") {
		return Result{false, "no kernel route back into tun0"}
	}
	return Result{true, "NAT + return route present"}
}

func (Network) Apply(ctx context.Context, c cfg.Config, log *logx.Logger) error {
	if err := os.WriteFile("/proc/sys/net/ipv4/ip_forward", []byte("1\n"), 0o644); err != nil {
		log.Dim("ip_forward write skipped: " + err.Error())
	}
	natArgs := []string{"-t", "nat", "-A", "POSTROUTING",
		"-s", c.Subnet, "!", "-d", c.Subnet, "-j", "MASQUERADE"}
	if out, _ := Output("iptables", "-t", "nat", "-L", "POSTROUTING", "-n"); !strings.Contains(out, c.Subnet) {
		if err := Run(ctx, log, "iptables", natArgs...); err != nil {
			return fmt.Errorf("masquerade failed: %w", err)
		}
	} else {
		log.Dim("masquerade already present")
	}
	if _, err := exec.LookPath("ufw"); err == nil {
		_ = Run(ctx, log, "ufw", "route", "allow", "in", "on", "tun0", "out", "on", "enp1s0", "from", c.Subnet)
		_ = Run(ctx, log, "ufw", "route", "allow", "in", "on", "enp1s0", "out", "on", "tun0", "to", c.Subnet)
	}
	unit := `[Unit]
Description=Restore VPN NAT rules (wizard)
After=network.target
[Service]
Type=oneshot
ExecStart=/sbin/iptables-restore /etc/iptables.wizard.rules
RemainAfterExit=yes
[Install]
WantedBy=multi-user.target
`
	_ = Run(ctx, log, "sh", "-c", "iptables-save > /etc/iptables.wizard.rules")
	if err := os.WriteFile("/etc/systemd/system/vpn-nat-restore.service", []byte(unit), 0o644); err == nil {
		_ = Run(ctx, log, "systemctl", "daemon-reload")
		_ = Run(ctx, log, "systemctl", "enable", "vpn-nat-restore")
	}
	out, _ := Output("ip", "route", "get", "10.8.0.2")
	if !strings.Contains(out, "tun0") {
		return fmt.Errorf("return route still missing after server restart; check server.conf route line")
	}
	log.OK("forwarding + NAT verified")
	return nil
}

// ClientBundle builds the import-ready .ovpn with domain+IP fallback remotes.
type ClientBundle struct{}

func (ClientBundle) ID() string    { return "client" }
func (ClientBundle) Title() string { return "Build phone/laptop file" }
func (ClientBundle) Why() string {
	return "One file with everything inside: keys, server address, and a backup address if DNS is blocked."
}

func clientCertPaths() (cert, key string, err error) {
	for _, pair := range [][2]string{
		{"/etc/openvpn/wizard-pki/client.crt", "/etc/openvpn/wizard-pki/client.key"},
		{"/etc/openvpn/easy-rsa/pki/issued/client.crt", "/etc/openvpn/easy-rsa/pki/private/client.key"},
	} {
		if fileExists(pair[0]) && fileExists(pair[1]) {
			return pair[0], pair[1], nil
		}
	}
	return "", "", fmt.Errorf("no client certificate found (run PKI step with client cert first)")
}

func (ClientBundle) Check(c cfg.Config) Result {
	ovpn := filepath.Join(c.OutDir, c.VPNUser+".ovpn")
	b, err := os.ReadFile(ovpn)
	if err != nil {
		return Result{false, "bundle missing"}
	}
	for _, r := range c.Remotes() {
		if !strings.Contains(string(b), r) {
			return Result{false, "bundle lacks: " + r}
		}
	}
	return Result{true, "bundle ready: " + ovpn}
}

func (ClientBundle) Apply(ctx context.Context, c cfg.Config, log *logx.Logger) error {
	certP, keyP, err := clientCertPaths()
	if err != nil {
		return err
	}
	read := func(p string) (string, error) {
		b, err := os.ReadFile(p)
		return strings.TrimSpace(string(b)), err
	}
	ca, err := read(filepath.Join(serverDir, "ca.crt"))
	if err != nil {
		return err
	}
	cert, err := read(certP)
	if err != nil {
		return err
	}
	key, err := read(keyP)
	if err != nil {
		return err
	}
	tls, err := read(filepath.Join(serverDir, "tls-crypt.key"))
	if err != nil {
		return err
	}
	var sb strings.Builder
	sb.WriteString("client\ndev tun\nproto tcp-client\n")
	for _, r := range c.Remotes() {
		sb.WriteString(r + "\n")
	}
	sb.WriteString(`resolv-retry infinite
server-poll-timeout 10
connect-retry 5 60
nobind
persist-key
persist-tun
remote-cert-tls server
auth-user-pass
auth-nocache
auth SHA256
data-ciphers AES-256-GCM:AES-128-GCM
data-ciphers-fallback AES-256-GCM
tls-version-min 1.2
verb 3
sndbuf 0
rcvbuf 0
tcp-nodelay
tun-mtu 1500
mssfix 1400
keepalive 10 60
explicit-exit-notify 0
<ca>
` + ca + "\n</ca>\n<cert>\n" + cert + "\n</cert>\n<key>\n" + key + "\n</key>\n<tls-crypt>\n" + tls + "\n</tls-crypt>\n")
	if err := os.MkdirAll(c.OutDir, 0o755); err != nil {
		return err
	}
	ovpn := filepath.Join(c.OutDir, c.VPNUser+".ovpn")
	if err := os.WriteFile(ovpn, []byte(sb.String()), 0o644); err != nil {
		return err
	}
	readme := "VPN login for " + c.VPNUser + "\nImport " + c.VPNUser + ".ovpn, user " +
		c.VPNUser + ". Website https://" + c.Host + "/ still works in browsers.\n"
	_ = os.WriteFile(filepath.Join(c.OutDir, "README-IMPORT.txt"), []byte(readme), 0o644)
	log.OK("bundle: " + ovpn)
	return nil
}
